### ISSUE TITLE
Feedback DownloadableFonts Problem

### ISSUE THREAD

**Issue by tcqq** [firatkarababa/DownloadableFonts#1]
## Hello, thank you your library, But I encountered a problem in use.
Do I need to have a cache, for example a local cache or a memory cache, when I get the font? Or do not need to cache, each time in accordance with the code in the sample directly get the font and set?

**Comment by firatkarababa** [comment]
Thanks, actually there is no need for any cache, just implement the callback to get the FontList instance which holds all of the downloadable fonts as Font objects and each Font object has all the necessary information about associated font. What problem exactly did you encounter when using the library?

**Comment by tcqq** [comment]
Ok, how can I know if this font is currently already downloaded?

**Comment by firatkarababa** [comment]
Actually you do not need to know, system will know and if it is already downloaded it will be provided by Font Provider. All you need to do is to make the font request by the query String formed with DownloadableFonts library. [Here ](https://android.jlelse.eu/downloadable-fonts-developers-guide-91b522e4d69e)is my tutorial on how to use Downloadable Fonts. You can use DownloadableFonts library to get the list of available fonts to download and form query Strings to make dynamic font requests.

**Comment by tcqq** [comment]
Thanks reply, I checked your `DownloadableFonts` library, i find the amount of data in the list is not very small, is support pagination loading now?

**Comment by firatkarababa** [comment]
Yes, you are right about the data loaded. I may need to add paging library, I will consider that.

**Comment by tcqq** [comment]
OK, I checked [google fonts](https://developers.google.com/fonts/docs/android) website, but did not find the paging function, google font api now supports paging?

**Comment by firatkarababa** [comment]
As far as I know no, it should be handled on library side

**Comment by tcqq** [comment]
Okay thank you.

**Comment by firatkarababa** [comment]
You are welcome. Also feel free to make pull requests.
